/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelRouteImport } from './routes/model'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiStatusStreamRouteImport } from './routes/api.status.stream'

const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusStreamRoute = ApiStatusStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiStatusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/model': typeof ModelRoute
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/status/stream': typeof ApiStatusStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/model': typeof ModelRoute
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/status/stream': typeof ApiStatusStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/model': typeof ModelRoute
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/status/stream': typeof ApiStatusStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/model' | '/api/status' | '/api/status/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/model' | '/api/status' | '/api/status/stream'
  id: '__root__' | '/' | '/model' | '/api/status' | '/api/status/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelRoute: typeof ModelRoute
  ApiStatusRoute: typeof ApiStatusRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/stream': {
      id: '/api/status/stream'
      path: '/stream'
      fullPath: '/api/status/stream'
      preLoaderRoute: typeof ApiStatusStreamRouteImport
      parentRoute: typeof ApiStatusRoute
    }
  }
}

interface ApiStatusRouteChildren {
  ApiStatusStreamRoute: typeof ApiStatusStreamRoute
}

const ApiStatusRouteChildren: ApiStatusRouteChildren = {
  ApiStatusStreamRoute: ApiStatusStreamRoute,
}

const ApiStatusRouteWithChildren = ApiStatusRoute._addFileChildren(
  ApiStatusRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelRoute: ModelRoute,
  ApiStatusRoute: ApiStatusRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
