/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelRouteImport } from './routes/model'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatusRouteImport } from './routes/api.status'
import { Route as ApiStateRouteImport } from './routes/api.state'
import { Route as ApiMapRouteImport } from './routes/api.map'
import { Route as ApiLidarRouteImport } from './routes/api.lidar'
import { Route as ApiFloorTopologyRouteImport } from './routes/api.floor-topology'
import { Route as ApiStatusStreamRouteImport } from './routes/api.status.stream'
import { Route as ApiStateStreamRouteImport } from './routes/api.state.stream'
import { Route as ApiModelMetaRouteImport } from './routes/api.model.meta'
import { Route as ApiModelFileRouteImport } from './routes/api.model.$file'
import { Route as ApiMapStreamRouteImport } from './routes/api.map.stream'
import { Route as ApiLidarStreamRouteImport } from './routes/api.lidar.stream'
import { Route as ApiFloorTopologyStreamRouteImport } from './routes/api.floor-topology.stream'

const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapRoute = ApiMapRouteImport.update({
  id: '/api/map',
  path: '/api/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLidarRoute = ApiLidarRouteImport.update({
  id: '/api/lidar',
  path: '/api/lidar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFloorTopologyRoute = ApiFloorTopologyRouteImport.update({
  id: '/api/floor-topology',
  path: '/api/floor-topology',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusStreamRoute = ApiStatusStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiStatusRoute,
} as any)
const ApiStateStreamRoute = ApiStateStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiStateRoute,
} as any)
const ApiModelMetaRoute = ApiModelMetaRouteImport.update({
  id: '/api/model/meta',
  path: '/api/model/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelFileRoute = ApiModelFileRouteImport.update({
  id: '/api/model/$file',
  path: '/api/model/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapStreamRoute = ApiMapStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiMapRoute,
} as any)
const ApiLidarStreamRoute = ApiLidarStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiLidarRoute,
} as any)
const ApiFloorTopologyStreamRoute = ApiFloorTopologyStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiFloorTopologyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/model': typeof ModelRoute
  '/api/floor-topology': typeof ApiFloorTopologyRouteWithChildren
  '/api/lidar': typeof ApiLidarRouteWithChildren
  '/api/map': typeof ApiMapRouteWithChildren
  '/api/state': typeof ApiStateRouteWithChildren
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/floor-topology/stream': typeof ApiFloorTopologyStreamRoute
  '/api/lidar/stream': typeof ApiLidarStreamRoute
  '/api/map/stream': typeof ApiMapStreamRoute
  '/api/model/$file': typeof ApiModelFileRoute
  '/api/model/meta': typeof ApiModelMetaRoute
  '/api/state/stream': typeof ApiStateStreamRoute
  '/api/status/stream': typeof ApiStatusStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/model': typeof ModelRoute
  '/api/floor-topology': typeof ApiFloorTopologyRouteWithChildren
  '/api/lidar': typeof ApiLidarRouteWithChildren
  '/api/map': typeof ApiMapRouteWithChildren
  '/api/state': typeof ApiStateRouteWithChildren
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/floor-topology/stream': typeof ApiFloorTopologyStreamRoute
  '/api/lidar/stream': typeof ApiLidarStreamRoute
  '/api/map/stream': typeof ApiMapStreamRoute
  '/api/model/$file': typeof ApiModelFileRoute
  '/api/model/meta': typeof ApiModelMetaRoute
  '/api/state/stream': typeof ApiStateStreamRoute
  '/api/status/stream': typeof ApiStatusStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/model': typeof ModelRoute
  '/api/floor-topology': typeof ApiFloorTopologyRouteWithChildren
  '/api/lidar': typeof ApiLidarRouteWithChildren
  '/api/map': typeof ApiMapRouteWithChildren
  '/api/state': typeof ApiStateRouteWithChildren
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/floor-topology/stream': typeof ApiFloorTopologyStreamRoute
  '/api/lidar/stream': typeof ApiLidarStreamRoute
  '/api/map/stream': typeof ApiMapStreamRoute
  '/api/model/$file': typeof ApiModelFileRoute
  '/api/model/meta': typeof ApiModelMetaRoute
  '/api/state/stream': typeof ApiStateStreamRoute
  '/api/status/stream': typeof ApiStatusStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/model'
    | '/api/floor-topology'
    | '/api/lidar'
    | '/api/map'
    | '/api/state'
    | '/api/status'
    | '/api/floor-topology/stream'
    | '/api/lidar/stream'
    | '/api/map/stream'
    | '/api/model/$file'
    | '/api/model/meta'
    | '/api/state/stream'
    | '/api/status/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/model'
    | '/api/floor-topology'
    | '/api/lidar'
    | '/api/map'
    | '/api/state'
    | '/api/status'
    | '/api/floor-topology/stream'
    | '/api/lidar/stream'
    | '/api/map/stream'
    | '/api/model/$file'
    | '/api/model/meta'
    | '/api/state/stream'
    | '/api/status/stream'
  id:
    | '__root__'
    | '/'
    | '/model'
    | '/api/floor-topology'
    | '/api/lidar'
    | '/api/map'
    | '/api/state'
    | '/api/status'
    | '/api/floor-topology/stream'
    | '/api/lidar/stream'
    | '/api/map/stream'
    | '/api/model/$file'
    | '/api/model/meta'
    | '/api/state/stream'
    | '/api/status/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelRoute: typeof ModelRoute
  ApiFloorTopologyRoute: typeof ApiFloorTopologyRouteWithChildren
  ApiLidarRoute: typeof ApiLidarRouteWithChildren
  ApiMapRoute: typeof ApiMapRouteWithChildren
  ApiStateRoute: typeof ApiStateRouteWithChildren
  ApiStatusRoute: typeof ApiStatusRouteWithChildren
  ApiModelFileRoute: typeof ApiModelFileRoute
  ApiModelMetaRoute: typeof ApiModelMetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map': {
      id: '/api/map'
      path: '/api/map'
      fullPath: '/api/map'
      preLoaderRoute: typeof ApiMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lidar': {
      id: '/api/lidar'
      path: '/api/lidar'
      fullPath: '/api/lidar'
      preLoaderRoute: typeof ApiLidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/floor-topology': {
      id: '/api/floor-topology'
      path: '/api/floor-topology'
      fullPath: '/api/floor-topology'
      preLoaderRoute: typeof ApiFloorTopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/stream': {
      id: '/api/status/stream'
      path: '/stream'
      fullPath: '/api/status/stream'
      preLoaderRoute: typeof ApiStatusStreamRouteImport
      parentRoute: typeof ApiStatusRoute
    }
    '/api/state/stream': {
      id: '/api/state/stream'
      path: '/stream'
      fullPath: '/api/state/stream'
      preLoaderRoute: typeof ApiStateStreamRouteImport
      parentRoute: typeof ApiStateRoute
    }
    '/api/model/meta': {
      id: '/api/model/meta'
      path: '/api/model/meta'
      fullPath: '/api/model/meta'
      preLoaderRoute: typeof ApiModelMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/$file': {
      id: '/api/model/$file'
      path: '/api/model/$file'
      fullPath: '/api/model/$file'
      preLoaderRoute: typeof ApiModelFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/stream': {
      id: '/api/map/stream'
      path: '/stream'
      fullPath: '/api/map/stream'
      preLoaderRoute: typeof ApiMapStreamRouteImport
      parentRoute: typeof ApiMapRoute
    }
    '/api/lidar/stream': {
      id: '/api/lidar/stream'
      path: '/stream'
      fullPath: '/api/lidar/stream'
      preLoaderRoute: typeof ApiLidarStreamRouteImport
      parentRoute: typeof ApiLidarRoute
    }
    '/api/floor-topology/stream': {
      id: '/api/floor-topology/stream'
      path: '/stream'
      fullPath: '/api/floor-topology/stream'
      preLoaderRoute: typeof ApiFloorTopologyStreamRouteImport
      parentRoute: typeof ApiFloorTopologyRoute
    }
  }
}

interface ApiFloorTopologyRouteChildren {
  ApiFloorTopologyStreamRoute: typeof ApiFloorTopologyStreamRoute
}

const ApiFloorTopologyRouteChildren: ApiFloorTopologyRouteChildren = {
  ApiFloorTopologyStreamRoute: ApiFloorTopologyStreamRoute,
}

const ApiFloorTopologyRouteWithChildren =
  ApiFloorTopologyRoute._addFileChildren(ApiFloorTopologyRouteChildren)

interface ApiLidarRouteChildren {
  ApiLidarStreamRoute: typeof ApiLidarStreamRoute
}

const ApiLidarRouteChildren: ApiLidarRouteChildren = {
  ApiLidarStreamRoute: ApiLidarStreamRoute,
}

const ApiLidarRouteWithChildren = ApiLidarRoute._addFileChildren(
  ApiLidarRouteChildren,
)

interface ApiMapRouteChildren {
  ApiMapStreamRoute: typeof ApiMapStreamRoute
}

const ApiMapRouteChildren: ApiMapRouteChildren = {
  ApiMapStreamRoute: ApiMapStreamRoute,
}

const ApiMapRouteWithChildren =
  ApiMapRoute._addFileChildren(ApiMapRouteChildren)

interface ApiStateRouteChildren {
  ApiStateStreamRoute: typeof ApiStateStreamRoute
}

const ApiStateRouteChildren: ApiStateRouteChildren = {
  ApiStateStreamRoute: ApiStateStreamRoute,
}

const ApiStateRouteWithChildren = ApiStateRoute._addFileChildren(
  ApiStateRouteChildren,
)

interface ApiStatusRouteChildren {
  ApiStatusStreamRoute: typeof ApiStatusStreamRoute
}

const ApiStatusRouteChildren: ApiStatusRouteChildren = {
  ApiStatusStreamRoute: ApiStatusStreamRoute,
}

const ApiStatusRouteWithChildren = ApiStatusRoute._addFileChildren(
  ApiStatusRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelRoute: ModelRoute,
  ApiFloorTopologyRoute: ApiFloorTopologyRouteWithChildren,
  ApiLidarRoute: ApiLidarRouteWithChildren,
  ApiMapRoute: ApiMapRouteWithChildren,
  ApiStateRoute: ApiStateRouteWithChildren,
  ApiStatusRoute: ApiStatusRouteWithChildren,
  ApiModelFileRoute: ApiModelFileRoute,
  ApiModelMetaRoute: ApiModelMetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
